// build.rs — sha256 the embedded runtime scripts at compile time so
// `embedded_install::EMBEDDED_RUNTIME_SCRIPTS` can pin the digests
// next to the `include_bytes!` payload without a hand-edit step.
//
// Emits `$OUT_DIR/embedded_sha.rs` which is `include!`'d from
// `src/embedded_install.rs`. The file looks like:
//
//   pub const SHA_INSTALL_CLONING_FISH_SH: &str = "abc123...";
//   pub const SHA_INSTALL_CLONING_SH:      &str = "def456...";
//   ...
//
// This is the source of truth for the runtime sha256 check in
// `resolve_runtime_script` — the runtime byte-compares the extracted
// file's hash against the same payload's hash; the build-time hash
// confirms the embedded payload matches what was on disk at build
// time (catches a stale-OUT_DIR situation across incremental builds).

use sha2::{Digest, Sha256};
use std::fs;
use std::io::Write;
use std::path::Path;

// Keep in lockstep with EMBEDDED_RUNTIME_SCRIPTS in
// src/embedded_install.rs. Any addition here MUST get a matching
// entry there + an `include_bytes!` payload + a const reference to
// the generated SHA constant.
const SCRIPTS: &[(&str, &str)] = &[
    // (file_name, const_suffix)
    ("install_cloning_fish.sh", "INSTALL_CLONING_FISH_SH"),
    ("install_cloning.sh", "INSTALL_CLONING_SH"),
    ("clone_voice_fish.sh", "CLONE_VOICE_FISH_SH"),
    ("clone_voice.sh", "CLONE_VOICE_SH"),
    ("fish_speech_synth.py", "FISH_SPEECH_SYNTH_PY"),
    ("cloning_synth.py", "CLONING_SYNTH_PY"),
];

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let scripts_dir = Path::new(&manifest_dir)
        .parent()
        .and_then(Path::parent)
        .expect("CARGO_MANIFEST_DIR has two parents")
        .join("scripts");

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
    out.push_str("// Re-runs whenever any embedded script changes.\n\n");

    for (file_name, const_suffix) in SCRIPTS {
        let path = scripts_dir.join(file_name);
        // Re-run build.rs whenever the script changes.
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|e| {
            panic!("build.rs: cannot read {}: {e}", path.display());
        });
        let mut h = Sha256::new();
        h.update(&bytes);
        let hex = hex_encode(&h.finalize());
        out.push_str(&format!(
            "pub const SHA_{const_suffix}: &str = \"{hex}\";\n"
        ));
    }

    let dest = Path::new(&out_dir).join("embedded_sha.rs");
    let mut f = fs::File::create(&dest).unwrap_or_else(|e| {
        panic!("build.rs: cannot create {}: {e}", dest.display());
    });
    f.write_all(out.as_bytes()).expect("write embedded_sha.rs");

    println!("cargo:rerun-if-changed=build.rs");
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0x0f) as usize] as char);
    }
    s
}
